<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get_package_config_dir</value>
  <value name="encodeutf8">true</value>
  <value name="body">IAlJRGF0YUhhc2hDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0SGFzaEN1cnNvcigpOwoKCS8vIEdl
dCBpbnB1dCB2YWx1ZXMKICAgCWlkYy5maXJzdCgpOwoJU3RyaW5nIGtleSA9IGlkYy5nZXRLZXko
KTsKCQoJVmFsdWVzIHZsID0gVmFsdWVzRW11bGF0b3IuZ2V0VmFsdWVzKHBpcGVsaW5lLCBrZXkp
OwoJU3RyaW5nIHBrZyA9IFNlcnZpY2UuZ2V0UGFja2FnZU5hbWUodmwpOwoJRmlsZSBmbCA9IFNl
cnZlckFQSS5nZXRQYWNrYWdlQ29uZmlnRGlyKHBrZyk7CglTdHJpbmcgY29uZmlnX2RpciA9IGZs
LmdldFBhdGgoKTsKCgl0cnkKCXsJCgkJLy8gR2V0IGxpc3Qgb2YgZmlsZXMgaW4gYSBnaXZlIGRp
cmVjdG9yeQogICAgICAgIEZpbGUgZm5hbWUgPSBuZXcgRmlsZShjb25maWdfZGlyKTsKICAgICAg
ICBTdHJpbmdbXSBmaWxlX2xpc3QgPSBmbmFtZS5saXN0KCk7CgkJZm5hbWUgPSBudWxsOwoJICAg
CWlkYy5maXJzdCgpOwoJCWlkYy5pbnNlcnRBZnRlcigiY29uZmlnX2ZpbGVfbGlzdCIsIGZpbGVf
bGlzdCk7Cgl9CgljYXRjaChFeGNlcHRpb24gZSkKCXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbihlLmdldE1lc3NhZ2UoKSk7Cgl9CgoJLy8gU2V0dXAgb3V0cHV0IG1lc3NhZ2UKCWlkYy5m
aXJzdCgpOwoJaWRjLmluc2VydEFmdGVyKCJwa2dfY29uZmlnIixjb25maWdfZGlyKTsKCglpZGMu
ZGVzdHJveSgpOw==</value>
</Values>
