<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">string_compare</value>
  <value name="encodeutf8">true</value>
  <value name="body">CnRyeSB7Ci8vIHBpcGVsaW5lCklEYXRhSGFzaEN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVs
aW5lLmdldEhhc2hDdXJzb3IoKTsKcGlwZWxpbmVDdXJzb3IuZmlyc3QoICJzdHJpbmcxIiApOwpT
dHJpbmcJczEgPSAoU3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwpwaXBlbGluZUN1
cnNvci5maXJzdCggInN0cmluZzIiICk7ClN0cmluZwlzMiA9IChTdHJpbmcpIHBpcGVsaW5lQ3Vy
c29yLmdldFZhbHVlKCk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKClN0cmluZyBhcmVFcXVh
bCA9IG5ldyBTdHJpbmcoIkZBTFNFIik7CgppZiAoIChzMSAhPSBudWxsKSAmJiAoczIgIT0gbnVs
bCkgKSB7CglpZiAoIHMxLmNvbXBhcmVUbyhzMikgPT0gMCkgewoJCWFyZUVxdWFsID0gIlRSVUUi
OwoJfQp9CgovLyBwaXBlbGluZQpJRGF0YUhhc2hDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBp
cGVsaW5lLmdldEhhc2hDdXJzb3IoKTsKcGlwZWxpbmVDdXJzb3JfMS5sYXN0KCk7CnBpcGVsaW5l
Q3Vyc29yXzEuaW5zZXJ0QWZ0ZXIoICJhcmVFcXVhbCIsIGFyZUVxdWFsICk7CnBpcGVsaW5lQ3Vy
c29yXzEuZGVzdHJveSgpOwoKfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCXRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQoK</value>
</Values>
