<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convert_time_to_milli</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglTdHJpbmcJZGF0ZVN0ciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAiZGF0ZVN0ciIgKTsKCVN0cmluZwlwYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJwYXR0ZXJuIiApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cmxv
bmcgbGQgPSAwOwp0cnkKewoJU2ltcGxlRGF0ZUZvcm1hdCBkZiA9IG5ldyBTaW1wbGVEYXRlRm9y
bWF0KHBhdHRlcm4pOwoJRGF0ZSBkID0gZGYucGFyc2UoZGF0ZVN0cik7CglsZCA9IGQuZ2V0VGlt
ZSgpOwp9CmNhdGNoKEV4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihl
LmdldE1lc3NhZ2UoKSk7Cn0KLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3Jf
MSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8x
LCAibG9ndGltZV9taWxsaSIsIExvbmcudG9TdHJpbmcobGQpICk7CnBpcGVsaW5lQ3Vyc29yXzEu
ZGVzdHJveSgpOwo=</value>
</Values>
