<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convert_milli_to_time</value>
  <value name="encodeutf8">true</value>
  <value name="body">IAovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1
cnNvcigpOwoJU3RyaW5nCWxvZ3RpbWVfbWlsbGkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgImxvZ3RpbWVfbWlsbGkiICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsK
CiAgICBMb25nIGwgPSBuZXcgTG9uZyhsb2d0aW1lX21pbGxpKTsKICAgIGxvbmcgbGQgPSBsLmxv
bmdWYWx1ZSgpOwogICAgamF2YS51dGlsLkRhdGUgZHQgPSBuZXcgamF2YS51dGlsLkRhdGUobGQp
OwoKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAidGltZXN0YW1wIiwg
ZHQudG9TdHJpbmcoKSApOwpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKCi8vU2FtcGxlIHRp
bWVzdGFtcCBpbiBtaWxsaXNlY29uZHMKLy8gTG9uZyBsID0gbmV3IExvbmcoIjEwNDkzMjU3NjU1
OTEiKTsgLy9BcHJpbCAzIDIwMDMgMDg6MjI6NDUKICAgIA==</value>
</Values>
