<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">write</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCgp0cnl7
DQoJCXBpcGVsaW5lQ3Vyc29yLmZpcnN0KCAic3RyaW5nX2RhdGEiKTsNCgkJU3RyaW5nIHN0cl9k
YXRhID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsNCiAgICAgICANCgkJcGlw
ZWxpbmVDdXJzb3IuZmlyc3QoICJkaXJfcGF0aCIpOw0KCQlTdHJpbmcgcGF0aCAgPSAoU3RyaW5n
KSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOw0KIA0KCQlwaXBlbGluZUN1cnNvci5maXJzdCgg
ImZpbGVfbmFtZSIpOw0KCQlTdHJpbmcgZmlsZV9uYW1lID0gKFN0cmluZykgcGlwZWxpbmVDdXJz
b3IuZ2V0VmFsdWUoKTsNCgoJCXBpcGVsaW5lQ3Vyc29yLmZpcnN0KCAib3B0aW9uIik7DQoJCVN0
cmluZyBvcHRpb24gPSAoU3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOw0KIA0KCQlT
dHJpbmcgZmlsZV9wYXRoID0gZmlsZV9uYW1lOw0KCgkJaWYgKHBhdGggIT0gbnVsbCkKCQl7CgkJ
CWZpbGVfcGF0aCA9IHBhdGggKyBGaWxlLnNlcGFyYXRvciArICBmaWxlX25hbWU7DQoJCX0KCgkJ
DQ1ib29sZWFuIGFwcGVuZF9mbGcgPSBmYWxzZTsKCQlpZiAob3B0aW9uICE9IG51bGwpCgkJewoJ
CQlpZiAob3B0aW9uLmVxdWFscygidHJ1ZSIpKQoJCQkJYXBwZW5kX2ZsZyA9IHRydWU7CgkJfQoJ
CUZpbGVXcml0ZXIgZncgPSBuZXcgRmlsZVdyaXRlcihmaWxlX3BhdGgsIGFwcGVuZF9mbGcpOw0K
CQlmdy53cml0ZShzdHJfZGF0YSArICJcbiIpOw0gICAgICAgIA0KCQlmdy5jbG9zZSgpOwoJCWZ3
ID0gbnVsbDsKDQogCQlwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCn0gCmNhdGNoKEV4Y2Vw
dGlvbiBlKQp7DQoJcGlwZWxpbmVDdXJzb3IubGFzdCgpOw0KCXBpcGVsaW5lQ3Vyc29yLmluc2Vy
dEFmdGVyKCJtZXNzYWdlIiwiRXJyb3IiKTsNCglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQp9
DQo=</value>
</Values>
