<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setProperty</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhSGFzaEN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRIYXNoQ3Vyc29yKCk7CQoJaWRjLmZp
cnN0KCJwcm9wZXJ0eSIpOwoJU3RyaW5nIHByb3BlcnR5X25hbWUgPSAoU3RyaW5nKWlkYy5nZXRW
YWx1ZSgpOwoJaWRjLmZpcnN0KCJ2YWx1ZSIpOwoJU3RyaW5nIHByb3BlcnR5X3ZhbHVlID0gKFN0
cmluZylpZGMuZ2V0VmFsdWUoKTsKCWlkYy5maXJzdCgiZmlsZSIpOwoJU3RyaW5nIGZpbGVfbmFt
ZSA9IChTdHJpbmcpaWRjLmdldFZhbHVlKCk7CgoJdHJ5Cgl7CgkJaWYgKHByb3BlcnR5X25hbWUg
IT0gbnVsbCkKCQl7CgkJCS8vIEdldCBzZXJ2ZXIgcHJvcGVydGllcwoJCQlQcm9wZXJ0aWVzIGNv
bmZpZyA9IG5ldyBQcm9wZXJ0aWVzKCk7CgkJCUlucHV0U3RyZWFtIGluX3N0cmVhbSA9IChJbnB1
dFN0cmVhbSkgbmV3IEZpbGVJbnB1dFN0cmVhbShmaWxlX25hbWUpOwoJCQljb25maWcubG9hZChp
bl9zdHJlYW0pOwoJCQljb25maWcuc2V0UHJvcGVydHkocHJvcGVydHlfbmFtZSwgcHJvcGVydHlf
dmFsdWUpOwoJCQkvLyBTdG9yIHByb3BlcnRpZXMgdG8gZmlsZQoJCQlPdXRwdXRTdHJlYW0gb3V0
ID0gKE91dHB1dFN0cmVhbSkgbmV3IEZpbGVPdXRwdXRTdHJlYW0oZmlsZV9uYW1lKTsKCQkJY29u
ZmlnLnN0b3JlKG91dCwgIlNlcnZlciBwcm9wZXJ0eSIpOwoKCQkJb3V0LmZsdXNoKCk7CgkJCW91
dC5jbG9zZSgpOwoJCQlpbl9zdHJlYW0uY2xvc2UoKTsKCgkJCWlkYy5maXJzdCgpOwoJCQlpZGMu
aW5zZXJ0QWZ0ZXIoICJtZXNzYWdlIiwgIlNldCBwcm9wZXJ0eSAtICIgKyBwcm9wZXJ0eV9uYW1l
ICk7CgkJfQoJCWVsc2UKCQl7CgkJCWlkYy5maXJzdCgpOwoJCQlpZGMuaW5zZXJ0QWZ0ZXIoICJt
ZXNzYWdlIiwgIkVycm9yIHNldHRpbmcgcHJvcGVydHkgLSAiICsgcHJvcGVydHlfbmFtZSApOwoJ
CX0KCX0KCWNhdGNoIChFeGNlcHRpb24gZSkKCXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bihlLmdldE1lc3NhZ2UoKSk7Cgl9CglpZGMuZGVzdHJveSgpOwo=</value>
</Values>
