<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">filter_file</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CglTdHJpbmcJZmlsZW5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImZpbGVuYW1lIiApOwoJU3RyaW5nCWZpbHRlciA9IElEYXRhVXRpbC5nZXRTdHJpbmco
IHBpcGVsaW5lQ3Vyc29yLCAiZmlsdGVyIiApOwoJU3RyaW5nCW9wdGlvbiA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAib3B0aW9uIiApOwpwaXBlbGluZUN1cnNvci5kZXN0
cm95KCk7ClN0cmluZyByZXN1bHQgPSAiRkFMU0UiOwpTdHJpbmcgc3RyID0gIiI7CgppZihvcHRp
b24uZXF1YWxzKCJwcmVmaXgiKSkKewoJc3RyID0gZmlsZW5hbWUuc3Vic3RyaW5nKDAsZmlsdGVy
Lmxlbmd0aCgpKTsKCWlmIChzdHIuZXF1YWxzKGZpbHRlcikpCgkJcmVzdWx0ID0gIlRSVUUiOwoJ
ZWxzZQoJCXJlc3VsdCA9ICJGQUxTRSI7Cn0KZWxzZSBpZiAob3B0aW9uLmVxdWFscygicG9zdGZp
eCIpKQp7CglzdHIgPSBmaWxlbmFtZS5zdWJzdHJpbmcoZmlsZW5hbWUubGVuZ3RoKCktZmlsdGVy
Lmxlbmd0aCgpLGZpbGVuYW1lLmxlbmd0aCgpKTsKCWlmIChzdHIuZXF1YWxzKGZpbHRlcikpCgkJ
cmVzdWx0ID0gIlRSVUUiOwoJZWxzZQoJCXJlc3VsdCA9ICJGQUxTRSI7Cgp9CmVsc2UKewoJcmVz
dWx0ID0gIlRSVUUiOwp9CgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8x
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEs
ICJyZXN1bHQiLCByZXN1bHQgKTsKcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cg==</value>
</Values>
