<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get_file_name</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAgCUlEYXRhSGFzaEN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRIYXNoQ3Vyc29yKCk7CgoJLy8g
R2V0IGlucHV0IHZhbHVlcwogICAJaWRjLmZpcnN0KCAiZmlsZV9uYW1lIiApOwoJU3RyaW5nIGZp
bGVfbmFtZSA9IChTdHJpbmcpIGlkYy5nZXRWYWx1ZSgpOwoJaWRjLmZpcnN0KCAicGF0aCIgKTsK
CVN0cmluZyBwYXRoID0gKFN0cmluZykgaWRjLmdldFZhbHVlKCk7CgoJZmlsZV9uYW1lID0gZmls
ZV9uYW1lLnJlcGxhY2UoJyMnLCcwJyk7CglmaWxlX25hbWUgPSBmaWxlX25hbWUucmVwbGFjZSgn
JicsJzAnKTsKCVN0cmluZyBmdWxsX3BhdGggPSBwYXRoOwoJZnVsbF9wYXRoICs9IEZpbGUuc2Vw
YXJhdG9yOwoJZnVsbF9wYXRoICs9IGZpbGVfbmFtZTsKCglpZGMuZmlyc3QoICJmaWxlIiApOwoJ
aWRjLmluc2VydEFmdGVyKCJ2YWx1ZSIsZnVsbF9wYXRoKTsKCWlkYy5kZXN0cm95KCk7Cg==</value>
</Values>
